---
- name: Add nginx repo key
  apt_key:
    url: "https://nginx.org/keys/nginx_signing.key"
    state: present

- name: Add the nginx repo
  apt_repository:
    repo: "deb http://nginx.org/packages/ubuntu/ {{ ansible_lsb.codename }} nginx"
    state: present

- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
  notify:
    - start nginx

- name: Copy over nginx config files
  template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Create the sites-available and sites-enabled folders
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - sites-available
    - sites-enabled

- name: Remove default config
  file:
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
  notify:
    - reload nginx

- name: Start nginx
  systemd:
    name: nginx
    enabled: yes
    masked: no
    state: started
