---
- hosts: all:!localhost
  remote_user: "{{ remote_user }}"
  become: true
  gather_facts: False
  pre_tasks:
    - name: Install Python for Ansible
      raw: bash -c "test -e /usr/bin/python3 || (apt -y update && apt install -y python3)"
      register: output
      changed_when:
        - output.stdout != ""
        - output.stdout != "\r\n"
    - name: Gather facts
      setup:
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        autoremove: yes
        state: latest
        update_cache: yes
        upgrade: yes
