---
- name: Install requirements
  apt:
    name:
      - python3-psycopg2
    state: latest

- name: Create user
  postgresql_user:
    db: "{{ database_name }}"
    name: "{{ database_username }}"
    password: "{{ database_password }}"
    expires: infinity
  become_user: postgres

- name: Create database
  postgresql_db:
    name: "{{ database_name }}"
    encoding: UTF-8
    owner: "{{ database_username }}"
  become_user: postgres
