---

- name: Create ssl certificates for www.edmontonpy.com
  command: certbot --nginx certonly -d www.edmontonpy.com -n
  args:
    creates: /etc/letsencrypt/live/www.edmontonpy.com/privkey.pem
  become: true

- name: Copy over uwsgi webserver configs
  template:
    src: etc/uwsgi/apps-available/www.edmontonpy.com.ini
    dest: /etc/uwsgi/apps-available/www.edmontonpy.com.ini
    owner: root
    group: root
    mode: 0644
  notify:
    restart uwsgi

- name: Enable uwsgi configs
  file:
    src: /etc/uwsgi/apps-available/www.edmontonpy.com.ini
    dest: /etc/uwsgi/apps-enabled/www.edmontonpy.com.ini
    state: link
  notify:
    restart uwsgi

- name: Copy over nginx configs
  template:
    src: "etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - www.edmontonpy.com
    - root_redirect
  notify:
    - reload nginx

- name: Enable nginx configs
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  with_items:
    - www.edmontonpy.com
    - root_redirect
  notify:
    - reload nginx

- name: Copy over uwsgi logrotate configs
  copy:
    src: etc/logrotate.d/uwsgi
    dest: /etc/logrotate.d/uwsgi
    owner: root
    group: root
    mode: 0644
