---
- name: Copy over uwsgi webserver configs
  template:
    src: etc/uwsgi/apps-available/www.edmontonpy.com.ini
    dest: /etc/uwsgi/apps-available/www.edmontonpy.com.ini
    owner: root
    group: root
    mode: 0644
  notify:
    restart uwsgi

- name: Enable uwsgi configs
  file:
    src: /etc/uwsgi/apps-available/www.edmontonpy.com.ini
    dest: /etc/uwsgi/apps-enabled/www.edmontonpy.com.ini
    state: link
  notify:
    restart uwsgi

- name: Copy over nginx configs
  template:
    src: etc/nginx/sites-available/www.edmontonpy.com
    dest: /etc/nginx/sites-available/www.edmontonpy.com
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Enable nginx configs
  file:
    src: /etc/nginx/sites-available/www.edmontonpy.com
    dest: /etc/nginx/sites-enabled/www.edmontonpy.com
    state: link
  notify:
    - reload nginx

- name: Copy over uwsgi logrotate configs
  copy:
    src: etc/logrotate.d/uwsgi
    dest: /etc/logrotate.d/uwsgi
    owner: root
    group: root
    mode: 0644
